### ISSUE TITLE
Download ASTER L1A data using earthaccess

### ISSUE THREAD

**Issue by ShashankBice** [nsidc/earthaccess#314] opened 2023-10-04 23:48 UTC
Hi folks, 
I want to see if there is a way I can programmatically download [ASTER L1A data](https://lpdaac.usgs.gov/products/ast_l1av003/) using earthaccess. I have been following the tutorials from the project Readme and ICESat-2 Hackweek tutorial, and I think I am able to search for granules for the particular dataset I need to download with the correct version specified. I am not able to download the data though.

Here is the command which I ran:
```
results = earthaccess.search_data(
    short_name = 'AST_L1A',
    version = '003',
    cloud_hosted = True,
    bounding_box = (-134.7,58.9,-133.9,59.2),
    temporal = ('2020-03-01','2020-04-30'),
    count = 100
)
```
I get two granules from this search. I then go ahead to download the 2 granules with the command:
`files = earthaccess.download(results, "./test_sample_data")`
This results in the below prompt, without download of any data:
```
Getting 2 granules, approx download size: 0.22 GB
QUEUEING TASKS | : 0it [00:00, ?it/s]
PROCESSING TASKS | : 0it [00:00, ?it/s]
COLLECTING RESULTS | : 0it [00:00, ?it/s]
```

A note, from the results description, it seems that this dataset is not yet cloud-hosted. If this info is helpful in debugging the issue.

Guidance here is very much appreciated :blush: I can provide more details as required tomorrow if needed to get to the bottom of this issue! 

Thanks,
Shashank

**Comment by asteiker** [comment] 2023-10-06 22:05
Hi @ShashankBice Thanks for reporting this! It looks like this ASTER L1A dataset does not support direct download; I only see options to use an ordering service from Earthdata Search. I'm hoping folks from the LP.DAAC can chime in to confirm: @amfriesz @BriannaLind Any advice you could offer for programmatic ASTER downloads?

**Comment by mfisher87** [comment] 2023-10-06 22:19
I'd also like to think about / ask:

* How can we identify collections that don't support direct download?
* Should we raise some `RuntimeError` in this case? What's a good user message to explain what's going on and how to move forward?

**Comment by danielfromearth** [comment] 2023-10-13 21:11
> Hi @ShashankBice Thanks for reporting this! It looks like this ASTER L1A dataset does not support direct download; I only see options to use an ordering service from Earthdata Search. I'm hoping folks from the LP.DAAC can chime in to confirm: @amfriesz @BriannaLind Any advice you could offer for programmatic ASTER downloads?

Hi @asteiker, I'm wondering: What you were looking at when you determined "I only see options to use an ordering service from Earthdata Search"?  

(The reason I ask is to assess whether issues encountered when attempting to download `DSCOVR_EPIC_L2_AER` data using `earthaccess` are perhaps caused by configurations similar to the ASTER L1A data being investigated in this issue.)

**Comment by BriannaLind** [comment] 2023-10-16 14:52
Yeah @asteiker is right, L1A needs to be 'staged' for delievery. @danielfromearth and  @mfisher87 I'm not sure where you would see this in the record, but in Earthdata Search you see this: 
![image](https://github.com/nsidc/earthaccess/assets/104585874/12dffa08-341e-4154-bb4b-511196c56c83) ..... the data actaully needs to be staged for delivery and then you can choose whether you want an hdf or a geotiff.

@ShashankBice You should be able to earthaccess to get AST_L1T v003 ("collectionConceptId": "C1000000320-LPDAAC_ECS") its the ASTER Level 1 precision terrain corrected registered at-sensor radiance V003

**Comment by ShashankBice** [comment] 2023-10-16 20:41
Hi everyone,
Thanks for looking into this, I really appreciate it!
Thanks @BriannaLind, unfortunately I won't be able to use L1T  imagery for our applications, where we want the raw L1A sensor data to derive topography using stereo processing routines. We are creating [interactive and executable photogrammetry tutorials](https://github.com/uw-cryo/asp_tutorials), and will use ASTER data for the first iteration of tutorials because it is publicly available. It would have been good if the L1A data could be accessed programmatically, which would have allowed users to pull in data for their region of interest and try out the tutorials, but I understand the limitations of tape storage and the need of the data to be staged before it can be accessed.

Thanks for all of your work on earthacces, it does help us in a lot of our data retrieval workflows,
Cheers,
Shashank

**Comment by BriannaLind** [comment] 2023-10-16 21:08
@betolink it would be interesting to explore how difficult it would be to add support for 'on-demand data' to 'earthaccess' 

@asteiker would be right to say that if data is 'on-demand' it cannot be accessed programmatically without first 'ordering/downloading it'?

**Comment by jhkennedy** [comment] 2023-10-16 21:23
@BriannaLind asynchronous requests take a little bit more work to handle well, and I don't know what tools/sdks/apis already exist for ASTER L1A, but at minimum, you'll need:
* an order method to submit the staging request
* an order status method to tell if the staging is done (ideally with in-between statuses)
* a watch method that regularly polls and waits for staging to be done
* an access method for the staged data, which is likely to be different from a standard access route. 

All that seems like something that should be handled by an Earthaccess "plugin" as it's likely very specific to each on demand dataset. 

I'd be interested in helping to scope this out as it would be cool to get [ASF's on-demand products](https://hyp3-docs.asf.alaska.edu/using/sdk/) accessible via Earthaccess too

**Comment by BriannaLind** [comment] 2023-10-17 00:10
Wow!  @jhkennedy thanks for breaking it down in a way that is so easy to understand! @mfisher87 I wonder if the [AppEEARS API](https://appeears.earthdatacloud.nasa.gov/api/?shell#introduction) would have a good interface/protocol model to build off of?

conversation adjacent question: what is the benefit of having a collection 'on demand' rather than distinct granules having distinct endpoints that are always accessible?  Is it cheaper to store?

**Comment by betolink** [comment] 2023-10-17 03:11
I was looking at https://cmr.earthdata.nasa.gov/search/granules.umm_json?short_name=AST_L1A  and going back to what @danielfromearth mentioned, there should be a way in CMR to tell how to access the data even if they have to go through a service. 

I like @jhkennedy's idea of having a plugin system to access ordering APIs. Not just for this dataset, I imagine having Harmony, AppEEars, OPeNDAP etc. How can we make it happen!?

**Comment by asteiker** [comment] 2023-10-17 20:19
I really like where this is going too, great thoughts @jhkennedy ! @betolink Yes, this has always been a sticking point when it comes to access URLs curated directly in a UMM-C record vs associated UMM-S or UMM-T records (i.e. it's not straightforward to surface _all_ access methods across these schemas, and we developed metadata mappings as part of our tools project for the NSIDC landing pages to address this). Regardless, I love this idea of plugins for given tools/services like ASF's ordering service, Harmony, AppEEARs, etc . I thought we had another Issue to surface associated services but maybe misremembering. We would want this to be driven by UMM-S/UMM-T <-> UMM-C associations as well.

**Comment by andypbarrett** [comment] 2023-10-25 18:26
Should we open a new issue to explore/sketch out how to create plugins and close this one?

**Comment by MattF-NSIDC** [comment] 2023-10-25 18:51
:100: 

Opening now!

**Comment by MattF-NSIDC** [comment] 2023-10-25 20:00
Opened #329 to track the work of improving this user experience and #328 to support alternate download mechanisms like the async one required for this dataset. 

I think we can consider this specific ticket resolved: ASTER L1A download is currently not supported. If anyone wants to continue discussion specific to this dataset, please re-open!

**Closed by MattF-NSIDC** 2023-10-25 20:00 UTC
